import csv, pathlib
from audit_metadata import OUT
NR='not_reported_in_accessible_source'
NA='not_applicable'
fields=['Prior paper','Problem','Dataset','Method','XAI','Leakage','Calibration','Ordinal','Subgroup','Difference from ours','Evidence boundary','Official source']
rows=[
['Li et al. (2021)','Employee-performance classification','Three linked internal HR tables from a publishing organization','Logistic regression; decision tree; naive Bayes','Permutation importance reported',NR,NR,'Nominal performance classification',NR,'Organization-specific comparison; present work joins ordinal failure analysis to an explicit evidence contract.','Official proceedings PDF; no claim of an exhaustive absence audit.','https://ieomsociety.org/singapore2021/papers/1188.pdf'],
['Adeniyi et al. (2022)','Employee-performance classification','Public HR table with 311 rows and 36 attributes','PCA; ANN; RF; DT; reported 80:20 split',NR,'Predictor exclusions and timing not sufficient to establish availability',NR,NR,NR,'Present work separately audits target aliases, target mapping and training-only evaluation.','Publisher full text. Existing title retained over conflicting Crossref deposit.','https://paradigmplus.itiud.org/volume3/number3/adeniyi/'],
['Putri and Sitohang (2026)','Employee-performance classification','INX employee data','Random Forest; multiple train/test proportions','Feature importance',NR,NR,'Ordered category names; order-aware evaluation not established by accessible source',NR,'Present work separates nested candidate selection from final evaluation and audits metric-specific extreme-class failures.','Publisher PDF methods/results; non-reporting is not proof of absence.','https://jacis.pubmedia.id/index.php/jacis/article/download/170/111'],
['Löfström et al. (2024)','Reliable local explanations with uncertainty','25 benchmark datasets','Calibrated Explanations based on Venn-Abers','Conditional feature explanations and counterfactuals',NR,'Central method component',NR,NR,'A new explanation method; present study audits existing exact-model SHAP and a declared probability-calibration path.','Publisher abstract and metadata; do not infer unseen evaluation controls.','https://www.sciencedirect.com/science/article/pii/S0957417424000198'],
['Sepúlveda et al. (2025)','Stability of local interpretability','Synthetic and real anomaly-detection data','Top-rank-weighted stability measure','SHAP-based feature-ranking consistency under small changes',NR,NR,NR,NR,'Local perturbation stability differs from fold/seed/training-resample comparisons and model-level deletion in the present audit.','Publisher abstract and section excerpts.','https://www.sciencedirect.com/science/article/pii/S0957417425005445'],
['Manafi Varkiani et al. (2025)','Employee attrition and contextual explanation','Italian financial-company employee records','Machine-learning case study; Random Forest explanation','SHAP contribution magnitude and direction',NR,NR,'Attrition outcome; not ordinal performance',NR,'Strong HR-XAI precedent; different outcome and organization, without evidence of the present shared audit contract in accessible material.','Publisher abstract and available methods excerpts.','https://www.sciencedirect.com/science/article/pii/S0957417425001976'],
['Rass and Dallinger (2026)','Detecting unwanted patterns in training data','Real-life and synthetic datasets','Prespecified rules; fuzzy reasoning; regression significance tests','Rule-based explainability','Data-bias/poisoning tests; not the same as prediction-time availability',NR,NR,'Rules can specify patterns; protected-group performance audit not established','Proposes data-testing machinery; present study evaluates how multiple system-audit views constrain claims on fixed HR evidence.','Publisher abstract and metadata; final publication year 2026 despite DOI containing 2025.','https://www.sciencedirect.com/science/article/pii/S0957417425037716'],
['Abusitta et al. (2024)','Taxonomy and limitations of XAI','Literature survey','Review and comparative taxonomy','Central topic',NA,NA,NA,NA,'General XAI guidance; present paper must show a concrete operational audit rather than treat a component list as novelty.','Publisher abstract and section excerpts; not a benchmark competitor.','https://www.sciencedirect.com/science/article/pii/S095741742401577X'],
['Kapoor et al. (2024), REFORMS','Reporting and reproducibility of ML-based science','Consensus and methodological literature','Checklist and guidelines','Reporting context','Transparent processing and validation guidance','Reporting context',NA,'Applicability depends on study question','Important prior protocol. Present contribution should be the executable linkage plus empirical interactions among audit findings, not the invention of transparent evaluation.','Author-maintained project and registered Science Advances metadata.','https://reforms.cs.princeton.edu/'],
['Bar-Gil et al. (2024)','Embedding AI ethics in HR analytics','Two organizational HR case studies','Comparative case-study analysis','Organizational governance context','Data-governance concerns; not a predictive leakage benchmark',NA,NA,'Ethical mitigation; not a subgroup-performance benchmark','Shows why technical diagnostics cannot settle organizational governance or employee consequences.','Publisher abstract and full-text excerpts.','https://www.sciencedirect.com/science/article/pii/S0160791X24000757'],
['Lones (2024)','Avoiding common ML practice errors','Tutorial and examples','Practical methodological guidance','Interpretation guidance','Evaluation and selection pitfalls',NR,NA,NA,'Broad practical precedent; present study instantiates connected checks in an ordinal HR setting.','Publisher tutorial identity and abstract; individual empirical comparisons are not inferred.','https://doi.org/10.1016/j.patter.2024.101046'],
['Present study','Auditing ordinal employee-performance prediction','INX; partial HRDataset_v14 protocol replication','Nested benchmark; objective/policy sensitivities; exact evidence identities','Exact-model grouped SHAP; stability; model-level deletion','Explicit assumptions; no verified timestamps; no leakage-free claim','Training-only calibration; multiple probability metrics','Ordinal models; QWK/MAE/RPS; per-class outcomes','Support-aware descriptive subgroup and separate proxy questions','Integration links conflicting findings to the evaluated system; no new predictor or deployment claim.','Frozen claim boundary; not an additional experimental result.','manuscript/main.md'],
]
with (OUT/'COMPARISON_TABLE.csv').open('w',encoding='utf-8',newline='') as f:
    w=csv.writer(f); w.writerow(fields); w.writerows(rows)
intro='# Prior-work comparison\n\nChecked 2026-09-09. This is a bounded, non-exhaustive comparison. `not_reported_in_accessible_source` means the inspected source did not establish that field; it does not mean the paper omitted it. `not_applicable` marks conceptual guidance or a different study type. No universal novelty conclusion follows from this table.\n\n'
md=intro+'| '+' | '.join(fields)+' |\n| '+' | '.join(['---']*len(fields))+' |\n'
md+='\n'.join('| '+' | '.join(str(c).replace('|','/') for c in r)+' |' for r in rows)+'\n'
(OUT/'COMPARISON_TABLE.md').write_text(md,encoding='utf-8')

kfields=['Paper','Year','Publisher keywords','Relevance to proposed keywords','Source']
krows=[
['Löfström et al.','2024','Explainable AI; Feature importance; Calibrated explanations; Venn-Abers; Uncertainty quantification; Counterfactual explanations','Supports explainable artificial intelligence and probability/explanation reliability terminology; do not claim our method is Calibrated Explanations.','https://www.sciencedirect.com/science/article/pii/S0957417424000198'],
['Abusitta et al.','2024','Explainable artificial intelligence; Machine Learning; Interpretability; Trusted artificial intelligence','Supports Explainable artificial intelligence; trusted AI would overstate our empirical boundary.','https://www.sciencedirect.com/science/article/pii/S095741742401577X'],
['Manafi Varkiani et al.','2025','Employee attrition; Prediction; Human Resources; Artificial Intelligence; Machine learning; Case study','Supports outcome-specific employee prediction and HR terminology; replace attrition with performance.','https://www.sciencedirect.com/science/article/pii/S0957417425001976'],
['Sepúlveda et al.','2025','Anomaly detection; Robust interpretability; Local interpretability; Stability measure','Supports explanation-evaluation language; anomaly detection is outside the present outcome.','https://www.sciencedirect.com/science/article/pii/S0957417425005445'],
['Rass and Dallinger','2026','Regression analysis; Fuzzy logic; Data bias; Explainable artificial intelligence; XAI','Supports XAI and data-quality audit terminology; data leakage is the more precise keyword for our availability controls.','https://www.sciencedirect.com/science/article/pii/S0957417425037716']]
with (OUT/'KEYWORD_COMPARISON.csv').open('w',encoding='utf-8',newline='') as f:
    w=csv.writer(f); w.writerow(kfields); w.writerows(krows)
print(f'Generated {len(rows)} comparison rows and {len(krows)} exact publisher keyword lists.')
